// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKcTDj6RLfDOgV0gpbBk_bJg7D-UWY2xk',
    appId: '1:477745290154:web:b43109a00021d93c69a9d3',
    messagingSenderId: '477745290154',
    projectId: 'foto-tidy',
    authDomain: 'foto-tidy.firebaseapp.com',
    storageBucket: 'foto-tidy.firebasestorage.app',
    measurementId: 'G-KM5B9HXGZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEWdOyUZ2J5_APu9DxiJhfPoa_qj8GpFU',
    appId: '1:477745290154:android:9f844634b831f42d69a9d3',
    messagingSenderId: '477745290154',
    projectId: 'foto-tidy',
    storageBucket: 'foto-tidy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZFKJu5illfa98UBxLWA_qQGNsRtEXY1Q',
    appId: '1:477745290154:ios:91562acf02051d3669a9d3',
    messagingSenderId: '477745290154',
    projectId: 'foto-tidy',
    storageBucket: 'foto-tidy.firebasestorage.app',
    iosBundleId: 'com.fototidy.fotoTidy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZFKJu5illfa98UBxLWA_qQGNsRtEXY1Q',
    appId: '1:477745290154:ios:91562acf02051d3669a9d3',
    messagingSenderId: '477745290154',
    projectId: 'foto-tidy',
    storageBucket: 'foto-tidy.firebasestorage.app',
    iosBundleId: 'com.fototidy.fotoTidy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKcTDj6RLfDOgV0gpbBk_bJg7D-UWY2xk',
    appId: '1:477745290154:web:32ce29950c519c9769a9d3',
    messagingSenderId: '477745290154',
    projectId: 'foto-tidy',
    authDomain: 'foto-tidy.firebaseapp.com',
    storageBucket: 'foto-tidy.firebasestorage.app',
    measurementId: 'G-YS1FT37GC7',
  );
}
